export const PRICING = {
  STARTER_MONTHLY: 99,
  STARTER_ANNUAL: 499,
  STARTER_ANNUAL_PER_MONTH: 41.58,
  STARTER_ANNUAL_SAVINGS: 689,
  UNLIMITED_MONTHLY: 297,
  UNLIMITED_ANNUAL: 2097,
  UNLIMITED_ANNUAL_PER_MONTH: 174.75,
  UNLIMITED_ANNUAL_SAVINGS: 1467,
  WEBSITE_ADDON: 750,
  format: (amount: number) => `$${amount}`,
} as const;
