project_id = "hrmhqybdsdngsvhjqwma"

[functions.avatar-generate-summary]
verify_jwt = true

[functions.avatar-generate-image]
verify_jwt = true

[functions.avatar-set-primary-image]
verify_jwt = true

[functions.launchpad-analyze]
verify_jwt = true

[functions.cal-webhook-handler]
verify_jwt = false

[functions.cal-create-managed-user]
verify_jwt = true

[functions.cal-refresh-token]
verify_jwt = true

[functions.invite-team-member]
verify_jwt = true
