-- Insert comprehensive marketing flow task templates across all 6 stages
-- Uses stage name lookup instead of hardcoded UUIDs for portability

INSERT INTO marketing_flow_task_templates (standard_stage_id, channel_name, title, priority)
SELECT s.id, v.channel_name, v.title, v.priority::task_priority
FROM (VALUES
-- FOUNDATIONS Stage (3 channels, 15 tasks)
('Foundations', 'Offer Creation', 'Use the AI Assistant to generate marketing ideas', 'high'),
('Foundations', 'Offer Creation', 'Review and select best offer ideas', 'high'),
('Foundations', 'Offer Creation', 'Finalize the primary offer', 'high'),
('Foundations', 'Offer Creation', 'Approve pricing and guarantee', 'normal'),
('Foundations', 'Offer Creation', 'Document final offer in client workspace', 'normal'),
('Foundations', 'Brand Assets', 'Go to Launchpad and complete brand assets section', 'high'),
('Foundations', 'Brand Assets', 'Upload logos, fonts, and colors', 'normal'),
('Foundations', 'Brand Assets', 'Add brand tone and messaging preferences', 'normal'),
('Foundations', 'Brand Assets', 'Confirm business description and services', 'normal'),
('Foundations', 'Access & Tracking Setup', 'Go to Launchpad and complete access section', 'high'),
('Foundations', 'Access & Tracking Setup', 'Share access to Facebook Business Manager', 'normal'),
('Foundations', 'Access & Tracking Setup', 'Share access to Google Ads', 'normal'),
('Foundations', 'Access & Tracking Setup', 'Share access to Google Analytics', 'normal'),
('Foundations', 'Access & Tracking Setup', 'Share access to website', 'normal'),
('Foundations', 'Access & Tracking Setup', 'Share access to domain registrar', 'normal'),
('Foundations', 'Access & Tracking Setup', 'Verify all access connections are active and tested', 'high'),

-- CREATE DEMAND Stage (6 channels, 27 tasks)
('Create Demand', 'Facebook & Instagram Ads', 'Define campaign objective', 'high'),
('Create Demand', 'Facebook & Instagram Ads', 'Identify target audiences', 'high'),
('Create Demand', 'Facebook & Instagram Ads', 'Create ad copy and creative', 'normal'),
('Create Demand', 'Facebook & Instagram Ads', 'Launch campaign', 'high'),
('Create Demand', 'Facebook & Instagram Ads', 'Monitor performance and optimize', 'normal'),
('Create Demand', 'YouTube Ads', 'Write ad script', 'normal'),
('Create Demand', 'YouTube Ads', 'Record or upload video', 'normal'),
('Create Demand', 'YouTube Ads', 'Choose targeting and placements', 'normal'),
('Create Demand', 'YouTube Ads', 'Add call-to-action', 'normal'),
('Create Demand', 'YouTube Ads', 'Launch and track performance', 'high'),
('Create Demand', 'LinkedIn Ads', 'Identify target roles and industries', 'high'),
('Create Demand', 'LinkedIn Ads', 'Create ad copy and visuals', 'normal'),
('Create Demand', 'LinkedIn Ads', 'Launch campaign', 'high'),
('Create Demand', 'LinkedIn Ads', 'Review performance weekly', 'normal'),
('Create Demand', 'Organic Social Media', 'Set up posting calendar', 'high'),
('Create Demand', 'Organic Social Media', 'Add brand templates', 'normal'),
('Create Demand', 'Organic Social Media', 'Schedule posts', 'normal'),
('Create Demand', 'Organic Social Media', 'Engage with comments and messages', 'normal'),
('Create Demand', 'Organic Social Media', 'Track growth metrics', 'normal'),
('Create Demand', 'PR & Partnerships', 'Identify outreach opportunities (podcasts, blogs, media)', 'normal'),
('Create Demand', 'PR & Partnerships', 'Write outreach messages', 'normal'),
('Create Demand', 'PR & Partnerships', 'Send initial outreach', 'high'),
('Create Demand', 'PR & Partnerships', 'Track responses and results', 'normal'),
('Create Demand', 'Cold Email Outreach', 'Create or upload contact list', 'high'),
('Create Demand', 'Cold Email Outreach', 'Write email sequence using AI Assistant', 'normal'),
('Create Demand', 'Cold Email Outreach', 'Verify sending domain', 'high'),
('Create Demand', 'Cold Email Outreach', 'Launch campaign', 'high'),
('Create Demand', 'Cold Email Outreach', 'Review replies and engagement', 'normal'),

-- CAPTURE DEMAND Stage (4 channels, 19 tasks)
('Capture Demand', 'Google Ads (Search)', 'Perform keyword research', 'high'),
('Capture Demand', 'Google Ads (Search)', 'Create ad groups and headlines', 'normal'),
('Capture Demand', 'Google Ads (Search)', 'Add extensions', 'normal'),
('Capture Demand', 'Google Ads (Search)', 'Set up conversion tracking', 'high'),
('Capture Demand', 'Google Ads (Search)', 'Launch and optimize weekly', 'high'),
('Capture Demand', 'Google Business Profile', 'Claim or verify listing', 'high'),
('Capture Demand', 'Google Business Profile', 'Add photos, hours, and services', 'normal'),
('Capture Demand', 'Google Business Profile', 'Write business description', 'normal'),
('Capture Demand', 'Google Business Profile', 'Post weekly updates', 'normal'),
('Capture Demand', 'Google Business Profile', 'Request reviews', 'normal'),
('Capture Demand', 'SEO', 'Audit current website', 'high'),
('Capture Demand', 'SEO', 'Optimize page titles and meta descriptions', 'normal'),
('Capture Demand', 'SEO', 'Create city or service landing pages', 'normal'),
('Capture Demand', 'SEO', 'Add schema markup', 'normal'),
('Capture Demand', 'SEO', 'Begin link-building plan', 'normal'),
('Capture Demand', 'Directory Listings', 'Add business to niche directories', 'normal'),
('Capture Demand', 'Directory Listings', 'Confirm NAP consistency', 'high'),
('Capture Demand', 'Directory Listings', 'Add description and services', 'normal'),
('Capture Demand', 'Directory Listings', 'Track traffic from directories', 'normal'),

-- CONVERT Stage (4 channels, 19 tasks)
('Convert', 'CRO (Website Optimization)', 'Review layout and clarity', 'high'),
('Convert', 'CRO (Website Optimization)', 'Add testimonials or case studies', 'normal'),
('Convert', 'CRO (Website Optimization)', 'Simplify calls-to-action', 'high'),
('Convert', 'CRO (Website Optimization)', 'Set up chat widget or lead form', 'normal'),
('Convert', 'CRO (Website Optimization)', 'Test conversion flow', 'high'),
('Convert', 'Lead Magnets', 'Use AI Assistant to brainstorm lead magnet ideas', 'high'),
('Convert', 'Lead Magnets', 'Create downloadable or video resource', 'normal'),
('Convert', 'Lead Magnets', 'Build landing page', 'normal'),
('Convert', 'Lead Magnets', 'Connect to CRM', 'normal'),
('Convert', 'Lead Magnets', 'Test opt-in flow', 'high'),
('Convert', 'Email Nurturing', 'Create automated email nurture campaign', 'high'),
('Convert', 'Email Nurturing', 'Write emails using AI Assistant', 'normal'),
('Convert', 'Email Nurturing', 'Add tags and automations', 'normal'),
('Convert', 'Email Nurturing', 'Connect to offer or call booking', 'normal'),
('Convert', 'Email Nurturing', 'Review open and click metrics', 'normal'),
('Convert', 'Retargeting Ads', 'Build custom audiences', 'high'),
('Convert', 'Retargeting Ads', 'Design testimonial or offer-based ads', 'normal'),
('Convert', 'Retargeting Ads', 'Launch on Meta and Google', 'high'),
('Convert', 'Retargeting Ads', 'Track conversions and frequency', 'normal'),

-- CLOSE Stage (3 channels, 13 tasks)
('Close', 'Sales Process', 'Map out current sales flow', 'high'),
('Close', 'Sales Process', 'Add or create sales script', 'normal'),
('Close', 'Sales Process', 'Add booking calendar', 'normal'),
('Close', 'Sales Process', 'Set follow-up automation', 'normal'),
('Close', 'Sales Process', 'Review pipeline weekly', 'normal'),
('Close', 'Payment & Transactions', 'Connect payment processor (Stripe, QuickBooks, etc.)', 'high'),
('Close', 'Payment & Transactions', 'Test transaction flow', 'high'),
('Close', 'Payment & Transactions', 'Verify receipts and notifications', 'normal'),
('Close', 'Reporting', 'Use the built-in Reporting Tool', 'high'),
('Close', 'Reporting', 'Review key metrics (leads, conversion rates, ad spend, ROI)', 'normal'),
('Close', 'Reporting', 'Share insights in weekly meeting', 'normal'),
('Close', 'Reporting', 'Identify trends and opportunities', 'normal'),
('Close', 'Reporting', 'Create custom dashboards', 'low'),

-- RETAIN & REACTIVATE Stage (4 channels, 18 tasks)
('Retain & Reactivate', 'Newsletters', 'Create monthly or quarterly newsletter', 'normal'),
('Retain & Reactivate', 'Newsletters', 'Segment contacts', 'normal'),
('Retain & Reactivate', 'Newsletters', 'Schedule send', 'normal'),
('Retain & Reactivate', 'Newsletters', 'Track open and click metrics', 'normal'),
('Retain & Reactivate', 'Reactivation Campaigns', 'Identify inactive clients', 'high'),
('Retain & Reactivate', 'Reactivation Campaigns', 'Use AI Assistant to write reactivation sequence', 'normal'),
('Retain & Reactivate', 'Reactivation Campaigns', 'Launch campaign', 'high'),
('Retain & Reactivate', 'Reactivation Campaigns', 'Track replies and sales', 'normal'),
('Retain & Reactivate', 'Referral Program', 'Create referral landing page', 'normal'),
('Retain & Reactivate', 'Referral Program', 'Write announcement email', 'normal'),
('Retain & Reactivate', 'Referral Program', 'Automate referral tracking', 'normal'),
('Retain & Reactivate', 'Referral Program', 'Send rewards', 'normal'),
('Retain & Reactivate', 'Review & Reputation', 'Request reviews post-purchase', 'normal'),
('Retain & Reactivate', 'Review & Reputation', 'Add automation for review requests', 'normal'),
('Retain & Reactivate', 'Review & Reputation', 'Collect and display on site', 'normal'),
('Retain & Reactivate', 'Loyalty & Retention Offers', 'Plan quarterly retention offer', 'normal'),
('Retain & Reactivate', 'Loyalty & Retention Offers', 'Announce via email', 'normal'),
('Retain & Reactivate', 'Loyalty & Retention Offers', 'Track returning clients and renewals', 'normal')
) AS v(stage_name, channel_name, title, priority)
JOIN standard_marketing_stages s ON s.name = v.stage_name;
